version: '3'

services:
  typescript-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - servicenetwork

networks:
  servicenetwork:
    driver: bridge
